name: Auto PR for dev branches

on:
  push:
    branches:
      - 'dev_*'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request via API
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
            const headBranch = context.ref.replace("refs/heads/", "");

            // PRがすでにあるか確認（重複防止）
            const { data: prs } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${headBranch}`,
              base: 'main'
            });

            if (prs.length === 0) {
              await github.rest.pulls.create({
                owner,
                repo,
                head: headBranch,
                base: 'main',
                title: `自動PR: ${headBranch} → main`,
                body: 'このPRは dev ブランチの push により自動作成されました。',
              });
              console.log("✅ PR created");
            } else {
              console.log("ℹ️ PR already exists. Skipping.");
            }
