name: Hello World Action

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
